name = "ecomm-gdg"
main = "src/index.js"
compatibility_date = "2024-03-28"
compatibility_flags = ["nodejs_compat"]

# Configuração do KV que serão criados na interface do Cloudflare
kv_namespaces = [
  { binding = "CACHE_KV", preview_id = "" },
  { binding = "SEARCH_KV", preview_id = "" },
  { binding = "SEARCH_METRICS", preview_id = "" },
  { binding = "PRODUCT_CACHE", preview_id = "" },
  { binding = "PERFORMANCE_METRICS", preview_id = "" }
]

# Configuração do Durable Objects para carrinho e sessão
# Será configurado ao criar e publicar o primeiro worker
[durable_objects]
bindings = [
  { name = "CART_DO", class_name = "CartDurableObject" },
  { name = "SESSION_DO", class_name = "SessionDurableObject" }
]

# Configuração do Turso (SQLite distribuído)
[vars]
TURSO_DB_URL = ""
TURSO_DB_TOKEN = ""
SITE_URL = "https://ecomm-gdg.pages.dev"
SEARCH_INDEX_TOKEN = "secret-token-for-indexing"
ENABLE_CACHE = "true"
DEBUG_MODE = "false"

# Rotas para personalização do comportamento por página
[[routes]]
pattern = "/produto/*"
custom_domains = true
content_type = "text/html;charset=UTF-8"
[routes.cache]
browser_ttl = 3600
edge_ttl = 86400
stale_while_revalidate = 172800

[[routes]]
pattern = "/produtos/*"
[routes.cache]
browser_ttl = 1800
edge_ttl = 7200
stale_while_revalidate = 86400

[[routes]]
pattern = "/api/search*"
[routes.cache]
browser_ttl = 60
edge_ttl = 300
stale_while_revalidate = 1800

# Assets estáticos com cache de longa duração
[[routes]]
pattern = "/_astro/*"
[routes.cache]
browser_ttl = 31536000
edge_ttl = 31536000
cache_key_fields = ["content-type", "content-encoding"]

# Configuração de otimização de imagens
[image_optimizer]
compression_ratio = 85

# Configurações avançadas de HTTP
[http]
compress = true
http2 = true
http3 = true
tls_1_3 = true

# Cabeçalhos de segurança globais
[[headers]]
for = "/*"
[headers.cache]
max_age = 31536000
[headers.response]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
Content-Security-Policy = "upgrade-insecure-requests"

# Compressão Brotli para JavaScript
[[headers]]
for = "/_astro/*.js"
[headers.response]
Content-Type = "application/javascript; charset=utf-8"
Content-Encoding = "br"
Cache-Control = "public, max-age=31536000, immutable"

# Compressão Brotli para CSS
[[headers]]
for = "/_astro/*.css"
[headers.response]
Content-Type = "text/css; charset=utf-8"
Content-Encoding = "br"
Cache-Control = "public, max-age=31536000, immutable"

# Compressão Brotli para fontes
[[headers]]
for = "/fonts/**/*.woff2"
[headers.response]
Cache-Control = "public, max-age=31536000, immutable"

# Configurações para Service Worker
[[headers]]
for = "/service-worker.js"
[headers.response]
Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
Service-Worker-Allowed = "/"